@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Nov 16 23:53:39 -0600 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto a0e5f0039e4a4eb1b7509cef4228c3e8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TbAlunbits_behav xil_defaultlib.TbAlunbits -log elaborate.log"
call xelab  -wto a0e5f0039e4a4eb1b7509cef4228c3e8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TbAlunbits_behav xil_defaultlib.TbAlunbits -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
