webtalk_init -webtalk_dir C:/Users/helbo/AppData/Roaming/Xilinx/Vivado/AluNbits/AluNbits.sim/sim_1/behav/xsim/xsim.dir/TbAlunbits_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 17 00:31:47 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b6615823-48f3-43c1-8ddb-4e354f1b80df" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a0e5f0039e4a4eb1b7509cef4228c3e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2495 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2376895847 -regid "" -xml C:/Users/helbo/AppData/Roaming/Xilinx/Vivado/AluNbits/AluNbits.sim/sim_1/behav/xsim/xsim.dir/TbAlunbits_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/helbo/AppData/Roaming/Xilinx/Vivado/AluNbits/AluNbits.sim/sim_1/behav/xsim/xsim.dir/TbAlunbits_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/helbo/AppData/Roaming/Xilinx/Vivado/AluNbits/AluNbits.sim/sim_1/behav/xsim/xsim.dir/TbAlunbits_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
